/**
 * Created by xiaer on 2018/9/25.
 */
let {generateRandomArray, generateNearlyOrderArray, printArray, testSort, copyArray} = require('../util/sortHelper')
let {selectionSort} = require('./selectionSort')
let {insertSort, insertSort2} = require('./insertSort')
let {bubbleSort, bubbleSort2} = require('./bubbleSort')
let {shellSort} = require('./shellSort')
let {mergeSort} = require('./mergeSort')
let {quickSort} = require('./quickSort')
let {quickSortBT} = require('./quickSortBT')
let {quickSortGo} = require('./quickSortGo')
let {quickSortWay} = require('./quickSortWay')

let a = generateRandomArray(50000, 1, 100000)
let b = generateNearlyOrderArray(10000, 1)
// printArray(selectionSort(a))

let a1 = copyArray(a)
let a2 = copyArray(a)
let a3 = copyArray(a)
let a4 = copyArray(a)
let a5 = copyArray(a)
let a6 = copyArray(a)
let a7 = copyArray(a)
let a8 = copyArray(a)
let a9 = copyArray(a)
let a10 = copyArray(a)
let a11 = copyArray(a)
testSort(selectionSort, a1)
testSort(insertSort, a2)
testSort(insertSort2, a3)
// testSort(bubbleSort, a4)
// testSort(bubbleSort2, a5)
testSort(shellSort, a6)
testSort(mergeSort, a7)
testSort(quickSort, a8)
testSort(quickSortBT, a9)
testSort(quickSortGo, a10)
testSort(quickSortWay, a11)

console.log('---------------------------------')

let b1 = copyArray(b)
let b2 = copyArray(b)
let b3 = copyArray(b)
let b4 = copyArray(b)
let b5 = copyArray(b)
let b6 = copyArray(b)
let b7 = copyArray(b)
let b8 = copyArray(b)
let b9 = copyArray(b)
testSort(selectionSort, b1)
testSort(insertSort, b2)
testSort(insertSort2, b3)
testSort(bubbleSort, b4)
testSort(bubbleSort2, b5)
testSort(shellSort, b6)
testSort(mergeSort, b7)
testSort(quickSort, b8)
testSort(quickSortBT, b9)